[WARNING] [2020-06-05 02:30:38,428:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:38,436:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:40,440:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:42,443:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:44,446:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:46,450:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:48,453:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:30:50,456:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 02:40:49,468:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Memory Exception -- restart with less ensemle_nbest: 25
[WARNING] [2020-06-05 02:40:49,567:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Memory Exception -- restart with less ensemle_nbest: 12
[WARNING] [2020-06-05 03:12:00,080:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Memory Exception -- restart with less ensemle_nbest: 6
[WARNING] [2020-06-05 03:12:00,244:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_35.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,258:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_31.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,263:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_30.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,268:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_29.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,273:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_28.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,278:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_27.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,283:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_26.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,287:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,292:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_24.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,297:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_23.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,302:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,306:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,311:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,316:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_19.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,321:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,326:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,331:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_16.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,336:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,341:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,345:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,350:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,355:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,360:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,364:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,369:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_7.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,374:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,379:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,384:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,388:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,394:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,398:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,422:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Memory Exception -- restart with less ensemle_nbest: 3
[WARNING] [2020-06-05 03:12:00,582:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_35.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,596:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_31.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,601:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_30.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,606:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_29.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,611:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_28.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,616:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_27.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,621:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_26.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,626:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,630:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_24.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,635:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_23.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,639:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,644:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,649:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,654:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_19.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,658:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,663:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,668:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_16.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,672:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,677:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,682:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,686:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,691:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,696:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,701:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,706:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_7.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,710:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,715:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,720:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,725:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,730:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:00,734:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:01,337:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:01,340:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:01,344:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-05 03:12:01,347:EnsembleBuilder(1):0060e5cd1de611a459d968ab68a66368] Error loading /tmp/autosklearn_tmp_28524_6112/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

Log_loss score 0.38537486415165306
