[WARNING] [2020-06-07 10:41:36,407:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:36,418:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:38,422:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:40,425:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:42,429:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:44,432:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:46,435:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:41:48,438:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] No models better than random - using Dummy Score!
[WARNING] [2020-06-07 10:50:33,351:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Memory Exception -- restart with less ensemle_nbest: 25
[WARNING] [2020-06-07 10:50:33,454:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Memory Exception -- restart with less ensemle_nbest: 12
[WARNING] [2020-06-07 11:15:25,800:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Memory Exception -- restart with less ensemle_nbest: 6
[WARNING] [2020-06-07 11:15:25,967:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:25,983:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:25,988:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:25,994:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_19.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,001:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,007:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,012:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_16.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,018:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,023:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,029:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_13.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,034:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,039:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,046:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_10.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,051:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,056:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,062:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_7.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,068:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,073:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,079:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,083:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

[WARNING] [2020-06-07 11:15:26,089:EnsembleBuilder(1):07ef92bdc09528d47549030109db32bf] Error loading /tmp/autosklearn_tmp_5851_8161/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError

Log_loss score 0.4336429351173126
